# commit to be tagged for the new release
commit = "HEAD"

project_name = "Omni"
github_repo = "siderolabs/omni"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

pre_release = false
previous = "v0.35.0"

[notes]

  [notes.machine-set-scaling]
    title = "Machine Set Scaling Parallelism"
    description = """\
It is now possible to adjust worker machine sets scaling and update strategies in the UI.
"""

  [notes.omnictl]
    title = "`omnictl` Version Warnings"
    description = """\
`omnictl` now warns that it has the different version from the backend.
"""

  [notes.labels]
    title = "Machine And Cluster Labels Completion"
    description = """\
The UI of search inputs was reworked. Now Omni suggests autocompletion for all existing machine and cluster labels.
It also displays the labels as colored boxes in the input to better match with what's shown in the list.
"""
